let - Hoisting with let keyword
JavaScript Hoisting

With let, you cannot use a variable before it is declared.

ReferenceError: Cannot access 'carName' before initialization